name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Копирую .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Установка зависимостей
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Генерация ключа
        run: php artisan key:generate
      - name: Права
        run: chmod -R 777 storage bootstrap/cache
      - name: Создание БД
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Запуск тестов
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_DRIVER: sync
        run: php artisan test
